# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5dd8a9ada012fcae103e1620ea31d991b3437159f05ed4f8210d6515b8099bc7378984e4d141904192400464ce51c0317426eab78719b7b3304773e078c7707e

test:
  secret_key_base: 2cb1c31a9336d2f6b6d8e05ed26f685883d0c34f1d4f75a49a34281bcb409841b2a4984e55100d9374a6f08be98eff65862d0e15353aedef41f7c0261364d39b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
